// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oldtimer.Api.Data;

#nullable disable

namespace Oldtimer.Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20230727113700_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Oldtimer.Api.Data.Car", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<int>("Colors")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SammlerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YearOfConstruction")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SammlerId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("Oldtimer.Api.Data.Sammler", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sammlers");
                });

            modelBuilder.Entity("Oldtimer.Api.Data.Car", b =>
                {
                    b.HasOne("Oldtimer.Api.Data.Sammler", "Sammler")
                        .WithMany("Cars")
                        .HasForeignKey("SammlerId");

                    b.Navigation("Sammler");
                });

            modelBuilder.Entity("Oldtimer.Api.Data.Sammler", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
